### PR TITLE
Enforcer | 6.5 | Improvement: Adding Proxy values for Enforcer

### PR DESCRIPTION
**Pull request by andreazorzetto**
Enforcer requires lower case env vars to set proxy urls.
Currently the ExtraEnvironmentVars set by the chart get converted in upper case and the Enforcer seems to ignore those settings unless provided in lower case.

### CODE REVIEW

**Comment by semyonmor** [comment]
@andreazorzetto 
why need the separate variables for http_proxy?
you can define it using:
extraEnvironmentVars:
  http_proxy: 1.1.1.1
  https_proxy: 1.1.1.1
  no_proxy: 1.1.1.1

image

**Comment by andreazorzetto** [comment]
The helper used for the extraEnvVars converts every variable to upper case and apparently the enforcer read lower case vars for proxy settings and ignore the other case

**Comment by andreazorzetto** [comment]
I added no_proxy in case we want to go ahead with this change

**Comment by semyonmor** [comment]
Fixed in PR #522

**Pull request closed without merging**
