### PR TITLE
Make it possible to add service labels

### PR DESCRIPTION
**Pull request by rgarcia89**

### CODE REVIEW

**Review by KoppulaRajender — APPROVED** [review]

**Comment by rgarcia89** [comment]
Any idea, when this is going to be merged?
@KoppulaRajender

**Comment by KoppulaRajender** [comment]
@rgarcia89  - Included similar changes in 6.5 branch with https://github.com/aquasecurity/aqua-helm/pull/454 - Will release both branches very soon.

**Review by semyonmor — APPROVED** [review]

**Comment by rgarcia89** [comment]
@semyonmor thanks for merging. Do you know when it will be pushed to your helm chart repo?

**Comment by semyonmor** [comment]
@rgarcia89 should be available for both 6.2 and 6.5
if not send me email

**Comment by rgarcia89** [comment]
@semyonmor I cannot find a new chart version. Version 6.2.7 does not include the changes. Am I missing something?
```
[raulgs@raulgs-xm2] (prodinfs) ~ # helm search repo aqua-helm/server --versions | grep 6.2
aqua-helm/server        6.2.7           6.2             A Helm chart for the Aqua Console components
aqua-helm/server        6.2.6           6.2             A Helm chart for the Aqua Console components
```

**Comment by semyonmor** [comment]
Please check now
aqua-helm/server	6.2.8        	6.2        	A Helm chart for the Aqua Console components
aqua-helm/server	6.2.7        	6.2        	A Helm chart for the Aqua Console components

**Comment by rgarcia89** [comment]
@semyonmor I somehow messed up the indentation.... sorry for that.
Fix is here https://github.com/aquasecurity/aqua-helm/pull/456

**Pull request merged**
