### PR TITLE
Fix to support rawk8s 1.19+ mutation certs

### PR DESCRIPTION
**Pull request by SaiMandalo**
Updated certificates generation needed for communicating kube-api server.
added subjectAltName to the server.conf file.

### CODE REVIEW

**Comment by SaiMandalo** [comment]
@xB-2048  @rshmiel

**Comment by rshmiel** [comment]
What version are you want to update?

**Comment by SaiMandalo** [comment]
> What version are you want to update?
> 
> > @xB-2048 @rshmiel

need this change for both 6.0 and 5.3.

**Comment by rshmiel** [comment]
> > What version are you want to update?
> > > @xB-2048 @rshmiel
> 
> need this change for both 6.0 and 5.3.

so you need to create corresponding PRs for those branches....

**Comment by SaiMandalo** [comment]
> > > What version are you want to update?
> > > > @xB-2048 @rshmiel
> > 
> > 
> > need this change for both 6.0 and 5.3.
> 
> so you need to create corresponding PRs for those branches....

Created 2 new PRs for 6.0 and 5.3 branches.

**Comment by rshmiel** [comment]
> > > > What version are you want to update?
> > > > > @xB-2048 @rshmiel
> > > 
> > > 
> > > need this change for both 6.0 and 5.3.
> > 
> > 
> > so you need to create corresponding PRs for those branches....
> 
> Created 2 new PRs for 6.0 and 5.3 branches.

once @xB-2048  or @KoppulaRajender approve i will merge the fixes

**Review by xB-2048 — APPROVED** [review]
looks good to me. @rshmiel Please merge the PR

**Pull request merged**
