### PR TITLE
add certificates

### PR DESCRIPTION
**Pull request by ebram-va**
Adds additional capability to add a `configmap` file containing a PEM certificate bundle.
- Mounts certificate to `/etc/ssl/certs` in both the scanner and server deployments
- Adds configurable settings to the values file
- Cleans up `volumes` and `volumemounts`, wrapping them in an `if` block

### CODE REVIEW

**Comment by ebram-va** [comment]
@semyonmor updated the PR against `6.5`.  Thanks!

**Comment by KoppulaRajender** [comment]
@ebram-va - the implementation is very functional, rather than having manual steps to create a configmap with certs and mounting, we can add them from secrets conditionally maybe we can use a `range` to load multiple custom certs to /etc/ssl/certs/
 by so adding simple instruction to readme will be easy.

**Comment by ebram-va** [comment]
@KoppulaRajender sure, I see how you've implemented it below, sorry I missed that earlier, just used to doing it as `configmaps`.  I'll try to get to that today or tomorrow, test it out on our dev instance and then update the PR!

**Comment by ebram-va** [comment]
@KoppulaRajender I am running this live now in our env.  The logic ended up making more sense just doing 1 key per secret instead of 1 secret with multiple keys.  Let me know if that's OK!

**Comment by semyonmor** [comment]
Hi @ebram-va 
Our apologies for the delay with your PR
Can you please rebase you branch to solve conflicts and we ill try to merge you PR tomorrow?

**Comment by ebram-va** [comment]
No problem, I did a rebase so let me know!

**Review by KoppulaRajender — APPROVED** [review]

**Review by semyonmor — APPROVED** [review]

**Pull request merged**
