### PR TITLE
Add NodeSelectors to check-db-upgrade job

### PR DESCRIPTION
**Pull request by gezb**
This PR adds NodeSeclctors to the check-db-upgrade job if they are configured

### CODE REVIEW

**Comment by semyonmor** [comment]
@gezb 
Why db selector?
global.db.nodeSelector
what we will happen if you will use the external database?

**Comment by gezb** [comment]
@semyonmor 
Good point - I did not think of that, would you suggest a new section in the values specific to the job? 

If so is it also worth having an enabled flag too so the job can be disabled

**Comment by semyonmor** [comment]
> global.db.nodeSelector

I can suggest to replace it to `global.web.nodeSelector`

**Comment by gezb** [comment]
OK I have pushed and update to change this to use `global.web.nodeSelector`

**Comment by semyonmor** [comment]
@gezb 
we added the changes as part of pr #742 
closing your PR

**Pull request closed without merging**
