### PR TITLE
Remove double sections in windows-enforcer template

### LINKED ISSUE #768: Windows Enforcer DS Chart referencing a pod property under a container level spec
Windows Enforcer Daemon Set Chart is referencing  "terminationGracePeriodSeconds" at line 99 of the yaml, [here.](https://github.com/aquasecurity/aqua-helm/blob/c158417c6178bc6d0e807f71702bfd9c8c27746d/enforcer/templates/enforcer-windows-daemonset.yaml#L99)
This terminationGracePeriodSeconds is a Pod property, under the container's level specs, which causes the Chart to fail since that property can't be found.
This property needs to be removed in order for Windows DaemonSet to work

### PR DESCRIPTION
**Pull request by zivshits**
Fix #768

### CODE REVIEW

**Comment by joshvermast** [comment]
This is actually breaking the ability to deploy this via Flux - cannot upvote this PR/request release fast enough!

**Comment by adishaull** [comment]
@zivshits please update kube-enforcer/Chart.yaml with the new enforcer version

**Comment by adishaull** [comment]
@zivshits  please add to trivyignore 
KSV119
KSV120
KSV121


and need to update README with the new version

**Comment by zivshits** [comment]
> @zivshits please add to trivyignore KSV119 KSV120 KSV121
> 
> and need to update README with the new version

What are these trivy ingores and how do they relate to the code?

**Review by semyonmor — APPROVED** [review]

**Pull request merged**
