### PR TITLE
Allow defining annotations on the web Service

### PR DESCRIPTION
**Pull request by nafarlee**

### CODE REVIEW

**Comment by agilgur5** [comment]
FYI, they rejected annotations without comment multiple times per #92 🤷

**Comment by nafarlee** [comment]
@agilgur5 That's unfortunate. There are **numerous** useful reasons to annotate a Service. It also feels arbitrarily asymmetric when they already allow annotating Ingress resources.

**Comment by agilgur5** [comment]
Oh I'm well aware, I'm just giving you a warning. Arbitrary is a good description of decisions/changes in this repo -- most things are closed with no comment or with a one-liner that doesn't make sense. I just happened to see this while checking in on my existing PRs and issues, but have already terminated a contract with them.

**Comment by nafarlee** [comment]
@agilgur5 Never say never, I guess!

**Comment by agilgur5** [comment]
@nafarlee with no comment here, no reason given for the change in position, and existing issues not responded to 🤷

**Pull request merged**
