### PR TITLE
fix/docs: dated TLS auth link in KubeEnforcer docs' ToC

### PR DESCRIPTION
**Pull request by agilgur5**
## Description

- 2d3b1eb109ab447f8453e5c21de34073cb170c64 changed the heading slightly,
  but didn't change the respective entry in the ToC
  - this updates the ToC entry to match the heading

## Tags

Follow-up to #93

### CODE REVIEW

**Comment by niso120b** [comment]
duplicate

**Comment by agilgur5** [comment]
@niso120b Er, this wasn't a duplicate... the bug [still very much exists in the docs](https://github.com/aquasecurity/aqua-helm/blame/1aec0675f585b131f277bcc27b182837f32c248d/kube-enforcer/README.md#L11). Also if it were a duplicate, I would expect you to add a reference to the PR or commit it duplicates. This does not duplicate any of my other PRs that you merged or closed.

Maybe you meant it had _conflicts_, which it almost certainly did with #108 that standardized the ToC and was merged first. I have rebased with the main branch and fixed those conflicts. It will likely conflict with #105 as well since that moves this section under its Pre-reqs section.

Please re-open this as it fixes a bug.

**Comment by agilgur5** [comment]
@niso120b fixed the merge conflict with #105 that was just merged as well. Should be no conflicts now and it was _not_ a duplicate.

**Comment by agilgur5** [comment]
Noting that this was re-opened and merged as #109

**Pull request closed without merging**
